### ISSUE TITLE
Support images in radio button like selector

### ISSUE THREAD

**Issue by jjrodrig** [IndabaConsultores/android-json-form-wizard#4]
Support a widget option selector based on images similar to "Select one grid" in https://opendatakit.org/help/form-design/examples/#image_prompts

https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/GridWidget.java

**Comment by jurkiri** [comment]
Added by @xcarmona https://github.com/IndabaConsultores/android-json-form-wizard/commit/2495f8a30d9be2513429270883cec28b6f1895e1
